// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoSoDdLI5oeyqt3Kd1cTyH_dvgMpGuE2Y',
    appId: '1:402307189464:web:3134692ea37d54b704e5ad',
    messagingSenderId: '402307189464',
    projectId: 'magic-english-b7acd',
    authDomain: 'magic-english-b7acd.firebaseapp.com',
    storageBucket: 'magic-english-b7acd.firebasestorage.app',
    measurementId: 'G-29CKFX4XDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Kn9-cpi9Cy6OgdQzvyZkgWmNOdPEDVg',
    appId: '1:402307189464:android:5c9b688bef41778704e5ad',
    messagingSenderId: '402307189464',
    projectId: 'magic-english-b7acd',
    storageBucket: 'magic-english-b7acd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9C87W6w6WXsHryAd-FVMIpcPYUArc9nw',
    appId: '1:402307189464:ios:e65b4511740760a004e5ad',
    messagingSenderId: '402307189464',
    projectId: 'magic-english-b7acd',
    storageBucket: 'magic-english-b7acd.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9C87W6w6WXsHryAd-FVMIpcPYUArc9nw',
    appId: '1:402307189464:ios:e65b4511740760a004e5ad',
    messagingSenderId: '402307189464',
    projectId: 'magic-english-b7acd',
    storageBucket: 'magic-english-b7acd.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoSoDdLI5oeyqt3Kd1cTyH_dvgMpGuE2Y',
    appId: '1:402307189464:web:79c1ecd9bed0a20904e5ad',
    messagingSenderId: '402307189464',
    projectId: 'magic-english-b7acd',
    authDomain: 'magic-english-b7acd.firebaseapp.com',
    storageBucket: 'magic-english-b7acd.firebasestorage.app',
    measurementId: 'G-XQLX059P2Z',
  );

}